-- Complete Database Schema for Society Tracker (Secured with Supabase Auth)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Profiles Table (replaces custom_users for auth, but keeps profile data)
CREATE TABLE IF NOT EXISTS public.custom_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    role TEXT[] DEFAULT '{"MEMBER-1"}',
    full_name TEXT,
    contact TEXT,
    gender TEXT,
    association TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Drop obsolete password column if it exists from previous custom implementations
ALTER TABLE public.custom_users DROP COLUMN IF EXISTS password;

-- 2. Channel Tasks
CREATE TABLE IF NOT EXISTS public.channel_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT,
    channel_name TEXT,
    title TEXT,
    priority TEXT,
    deadline TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Notices
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. My Tasks
CREATE TABLE IF NOT EXISTS public.my_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.custom_users(id) ON DELETE CASCADE,
    name TEXT,
    description TEXT,
    priority INTEGER DEFAULT 1,
    deadline_date TEXT,
    deadline_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================================================
-- ROW LEVEL SECURITY POLICIES
-- =============================================================================

ALTER TABLE public.custom_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.channel_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.my_tasks ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to avoid errors)
DROP POLICY IF EXISTS "Allow all access to custom_users" ON public.custom_users;
DROP POLICY IF EXISTS "Allow all access to channel_tasks" ON public.channel_tasks;
DROP POLICY IF EXISTS "Allow all access to notices" ON public.notices;
DROP POLICY IF EXISTS "Allow all access to my_tasks" ON public.my_tasks;

DROP POLICY IF EXISTS "Authenticated users can read profiles" ON public.custom_users;
DROP POLICY IF EXISTS "Users can update own profile" ON public.custom_users;
DROP POLICY IF EXISTS "Admins can update any profile" ON public.custom_users;
DROP POLICY IF EXISTS "Authenticated users full access to channel_tasks" ON public.channel_tasks;
DROP POLICY IF EXISTS "Authenticated users full access to notices" ON public.notices;
DROP POLICY IF EXISTS "Users can only access their own tasks" ON public.my_tasks;

-- Profiles (custom_users)
-- Anyone authenticated can read profiles
CREATE POLICY "Authenticated users can read profiles" ON public.custom_users FOR SELECT USING (auth.role() = 'authenticated');
-- Users can update their own profile
CREATE POLICY "Users can update own profile" ON public.custom_users FOR UPDATE USING (id = auth.uid());
-- Admins can update any profile (e.g. changing roles)
CREATE POLICY "Admins can update any profile" ON public.custom_users FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.custom_users WHERE id = auth.uid() AND 'ADMIN' = ANY(role))
);

-- Tasks & Notices
CREATE POLICY "Authenticated users full access to channel_tasks" ON public.channel_tasks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access to notices" ON public.notices FOR ALL USING (auth.role() = 'authenticated');

-- My Tasks (Global visibility and access for all users as requested)
CREATE POLICY "Users can access all tasks" ON public.my_tasks FOR ALL USING (auth.role() = 'authenticated');

-- =============================================================================
-- ADMIN FUNCTIONS (Bypassing RLS safely)
-- =============================================================================

-- Function to create initial admin or reset admin if needed
CREATE OR REPLACE FUNCTION setup_initial_admin(admin_email TEXT, admin_password TEXT)
RETURNS void
SECURITY DEFINER
AS $$
DECLARE
  new_id UUID := gen_random_uuid();
  existing_id UUID;
BEGIN
  -- Check if user exists in auth.users
  SELECT id INTO existing_id FROM auth.users WHERE email = admin_email;
  
  IF existing_id IS NULL THEN
    -- Check if the email is already in custom_users
    SELECT id INTO existing_id FROM public.custom_users WHERE email = admin_email;
    IF existing_id IS NOT NULL THEN
      new_id := existing_id;
    END IF;

    -- Insert into auth.users directly (without instance_id to avoid schema errors)
    INSERT INTO auth.users (
      id, aud, role, email, encrypted_password, email_confirmed_at, 
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    )
    VALUES (
      new_id, 'authenticated', 'authenticated', 
      admin_email, crypt(admin_password, gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"]}', '{}', now(), now()
    );

    -- Create profile for admin
    INSERT INTO public.custom_users (id, email, role, full_name)
    VALUES (new_id, admin_email, '{"ADMIN"}', 'System Admin')
    ON CONFLICT (email) DO UPDATE SET role = '{"ADMIN"}', id = EXCLUDED.id;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Execute to create the default admin user
SELECT setup_initial_admin('admin@society.com', 'admin123');

-- RPC for AdminPanel to add a new user
CREATE OR REPLACE FUNCTION admin_add_user(new_email TEXT, new_password TEXT, new_roles TEXT[])
RETURNS UUID
SECURITY DEFINER
AS $$
DECLARE
  new_user_id UUID;
  is_admin BOOLEAN;
  existing_id UUID;
BEGIN
  -- Verify caller is admin
  SELECT EXISTS (
    SELECT 1 FROM public.custom_users 
    WHERE id = auth.uid() AND 'ADMIN' = ANY(role)
  ) INTO is_admin;

  IF NOT is_admin THEN
    RAISE EXCEPTION 'Access Denied: Only Admins can create users.';
  END IF;

  SELECT id INTO existing_id FROM auth.users WHERE email = new_email;
  IF existing_id IS NOT NULL THEN
    RAISE EXCEPTION 'User with this email already exists.';
  END IF;

  SELECT id INTO existing_id FROM public.custom_users WHERE email = new_email;
  IF existing_id IS NOT NULL THEN
     new_user_id := existing_id;
  ELSE
     new_user_id := gen_random_uuid();
  END IF;

  INSERT INTO auth.users (
    id, aud, role, email, encrypted_password, email_confirmed_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  VALUES (
    new_user_id, 'authenticated', 'authenticated', 
    new_email, crypt(new_password, gen_salt('bf')), now(),
    '{"provider":"email","providers":["email"]}', '{}', now(), now()
  );

  INSERT INTO public.custom_users (id, email, role)
  VALUES (new_user_id, new_email, new_roles)
  ON CONFLICT (email) DO UPDATE SET role = EXCLUDED.role, id = EXCLUDED.id;

  RETURN new_user_id;
END;
$$ LANGUAGE plpgsql;

-- RPC for AdminPanel to delete a user securely
CREATE OR REPLACE FUNCTION admin_delete_user(target_user_id UUID)
RETURNS void
SECURITY DEFINER
AS $$
DECLARE
  is_admin BOOLEAN;
BEGIN
  -- Verify caller is admin
  SELECT EXISTS (
    SELECT 1 FROM public.custom_users 
    WHERE id = auth.uid() AND 'ADMIN' = ANY(role)
  ) INTO is_admin;

  IF NOT is_admin THEN
    RAISE EXCEPTION 'Access Denied: Only Admins can delete users.';
  END IF;

  -- Delete from auth.users (cascades to custom_users)
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$$ LANGUAGE plpgsql;
